add POPM frame with test
lawik/id3vx pull request #14
Opened 2022-06-08 09:27 UTC by m13m

2022-08-23 10:52 UTC, m13m commented
stole some of the counter stuff from PCNT frame.

2022-08-23 20:46 UTC, lawik commented on test/id3vx/encoding_test.exs
> +    assert email == frame.data.email
not checking rating or count

2022-08-25 14:00 UTC, lawik commented
Is it done? Please provide a comment if requesting review.

2022-08-25 15:20 UTC, m13m commented
yes @lawik this is also ready for review.

2022-09-07 11:40 UTC, m13m commented
This PR is review ready ✨ 

- added test with id3v2 cli for existence of POPM frame 

- ffmpeg doesn't support particular frame.

2022-09-08 11:04 UTC, lawik requested changes

2022-09-08 11:04 UTC, lawik commented on lib/id3vx/frame.ex
> +    frame_binary = [email, <<0, 0>>, <<rating::size(8)>>, <<counter::size(counter_size)>>]
Should be single null byte, right?

2022-09-08 11:04 UTC, lawik commented on lib/id3vx/frame.ex
> +    [email, rest] = :binary.split(data, <<0, 0>>)
Single null byte :)

2022-09-17 08:22 UTC, m13m commented
FIXED the null byte issue and resolved the conflict

as it had no other issue apart from that I merging this PR.

2022-09-17 08:22 UTC, merged