add COMR frame with test
lawik/id3vx pull request #23
Opened 2022-06-22 11:25 UTC by m13m

2022-08-01 06:27 UTC, lawik requested changes
Looks good, just a few things.

2022-08-01 06:27 UTC, lawik commented on lib/id3vx/frame.ex
> +    contact_url = convert_string(:iso8859_1, contact_url)
This conversion should also be applied to:

- price
- valid until
- picture mime

2022-08-01 06:27 UTC, lawik commented on lib/id3vx/frame.ex
> +    IO.inspect(recieved_as)
Njet!
No inspects :)

2022-08-15 10:54 UTC, m13m commented
ready for merge ✨

2022-08-16 06:45 UTC, merged